pipeline {
    agent any

    tools {
        maven 'maven'  // Jenkins tool name
        jdk 'jdk17'    // Jenkins tool name
    }

    environment {
        SONAR_PROJECT_KEY  = 'devsecops-java'
        SONAR_PROJECT_NAME = 'devsecops-java'
    }

    stages {

        stage('Build & Compile') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Unit Tests') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                sh 'mvn package -DskipTests'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh 'mvn sonar:sonar ' +
                       "-Dsonar.projectKey=${SONAR_PROJECT_KEY} " +
                       "-Dsonar.projectName=${SONAR_PROJECT_NAME} " +
                       "-Dsonar.java.binaries=target/classes"
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
